name: Test Codes
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
on: push
jobs:
  test:
    # https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job
    runs-on: ubuntu-latest
    steps:
      - name: Download Codes
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Run tests
        run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Download Codes
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: deploy
        run: echo "deploying ..."
